image: plainerman/qemuriscv:oxtra

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - libs/spdlog/CMakeFiles/
    - libs/spdlog/libspdlog.a

build:
  stage: build
  script:
    - cmake -D CMAKE_BUILD_TYPE=release -D CMAKE_C_COMPILER=/opt/riscv/bin/riscv64-unknown-linux-gnu-gcc -D CMAKE_CXX_COMPILER=/opt/riscv/bin/riscv64-unknown-linux-gnu-g++ .
    - make
  artifacts:
    paths:
      - oxtra
      - test/unit_tests

unit_test:
    stage: test
    dependencies:
      - build
    script:
      - set +e # disable exit on error
      - qemu-riscv64 test/unit_tests
      - set -e # enable exit on error
      - qemu-riscv64 test/unit_tests -r junit > test/report.xml
    artifacts:
      reports:
        junit: test/report.xml

integration_test:
    stage: test
    dependencies:
      - build
    script:
      - shelltest --version
      - shelltest --all --timeout=30 --threads=4 test/integration/*.otest --with="qemu-riscv64 oxtra"